### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Nizzlay** [kogakure/gulp-tutorial#10]
Thank you so much for the gulp-tutorial.
First one I found that was actually useful.

One question though. The tutorial is from a couple of years ago. Has anything changed? Could you do an updated version? 
I'm wondering about the versions you used. Almost all of them have new releases now. And I believe quite a lot of new plugins are available. What has changed in your workflow since then?

**Comment by kogakure** [comment]
Hi, your question is a valid one. I haven’t touched the tutorial for a while. I have currently three websites running with a similar setup. Two of my websites run now with [Hugo](https://gohugo.io/), one still with Jekyll (in progress of being migrated, because Hugo is myriads faster).

Things **I changed** in my private setup (compared to the tutorial):

- SVG instead of Webfonts (`gulp-svg-sprite`)
- Linting JavaScript with `eslint` instead of `jshint`
- More PostCSS plugins
- Added `yarn`
- Responsive images with `gulp-responsive` on one of my websites

The rest looks still the same. Why change a running system without having a need?

You can see my current setup [here](https://github.com/kogakure/hugo-stefanimhoff.de) and [here](https://github.com/kogakure/jekyll-kogakure.de).

In my upcoming migrated website, I added Gulp 4, [Babel](https://babeljs.io/), ES6, [Webpack](https://webpack.js.org/). I took some ideas from [victor-hugo](https://github.com/netlify/victor-hugo).

The migration is not finished, so there might be more changes. I will remove the **lost** grid system and use **CSS Grid Layout**.

### Updating?

Regarding your question of updating the tutorial: I *might* do another article, when **Gulp 4** is officially released. 

I stopped updating the tutorial, because the work effort is *tremendous*. 16 articles, 122 code examples, 86000 characters, 12500 words, 1 hour reading time (and × 2, because of a copy on Medium). Updating all code examples took more than 6 hours last time.

That’s why I added the fixed version numbers to the tutorial, to make sure it still runs in the future.

I hope when people have finished my tutorial, they are capable to add other plugins, workflows and update modules themselves.

**But** I updated the repository today, so everything runs with the freshest versions (still the same stack). I added more documentation to the `README`.

Are you missing anything? A workflow, or task you would like to achieve?

**Comment by Nizzlay** [comment]
I've read interesting things about UnCSS. For which I've found gulp-uncss, but that seems to be depricated.

That's something I'd like to add to my build task

**Comment by kogakure** [comment]
Hi, I’ve never used UnCSS, because I write exactly the CSS I need and include only this where needed, but as far as I read on the gulp plugins page, it’s only deprecated, because it’s now a PostCSS plugin. There is an easy to understand documentation of how to include it in the PostCSS process right below the deprecation message: https://github.com/ben-eb/gulp-uncss. You add `postcss-uncss` to the PostCSS plugins (probably at the very end of the plugins list) and run it agains the HTML files to check against.
