### ISSUE TITLE
browserify doesn't seem to watch

### ISSUE THREAD

**Issue by jpeg729** [kogakure/gulp-tutorial#2]
I've been reading through your tuto trying to make sense of it and see what I can take for my own project.
I can't see how you get browserify to watch for changes, nor where you tell browsersync to reload after rebuilding the changes.

It will watch if (global.isWatching)
https://github.com/kogakure/gulp-tutorial/blob/master/gulp/tasks/development/scripts.js#L49
but isWatching isn't set anywhere in this repository.

I guess browserSync.reload should be done in bundle https://github.com/kogakure/gulp-tutorial/blob/master/gulp/tasks/development/scripts.js#L32

**Comment by kogakure** [comment]
I use the build in server of BrowserSync, all watching is done directly in my config file. I only trigger manual reload for Jekyll, because I want it to do it only once after all files were generated:

```javascript
browsersync: {
    development: {
      server: {
        baseDir: [development, build, src]
      },
      port: 9999,
      files: [
        developmentAssets + '/css/*.css',
        developmentAssets + '/js/*.js',
        developmentAssets + '/images/**',
        developmentAssets + '/fonts/*'
      ]
    },
    production: {
      server: {
        baseDir: [production]
      },
      port: 9998
    }
  },
```

Watched files are in `files: [ … ]`. I don’t use the `global.isWatching` which is taken from [gulp-starter](https://github.com/greypants/gulp-starter).
